### ISSUE TITLE
Issue desktopnotify

### ISSUE THREAD

**Issue by sailorzhang** [coofly/qx-chat#2]
line 120, n.colse -> n.close

**Comment by coofly** [comment]
最新版这个问题应该已经修复了

**Comment by sailorzhang** [comment]
你再看一下，问题还在！

**Comment by coofly** [comment]
我这边无法重现，你用的什么浏览器？另外把出错部分的上下文贴一下

**Comment by sailorzhang** [comment]
//有的chrome浏览器下colse无效，貌似不统一
                        if (n.colse){
                            n.close();
                        } else if(n.cancel) {
                            n.cancel();
                        }
close写错了

**Comment by coofly** [comment]
已经修正！谢谢啦，最近比较忙，都没什么时间弄
这两天忙得差不多了
coofly/qx-chat@4a0d0fa61235ce6e7657cfe966ec7985f06b411e
